### Login  1
POST localhost:8080/auth/login
Accept-Language: UZ
Content-Type: application/json
#user

{
  "email": "shakhzodallayorov23@gmail.com",
  "password": "User1234@"
}


### Login 2
POST localhost:8080/auth/login
Accept-Language: UZ
Content-Type: application/json
#user

{
  "email": "asadbekxojamurodov68@gmail.com",
  "password": "User1234@"
}


### Login Admin
POST localhost:8080/auth/login
Accept-Language: UZ
Content-Type: application/json
#admin1

{
  "email": "Adminceek123@gmail.com",
  "password": "User1234@"
}



####Registration
POST localhost:8080/auth/registration
Accept-Language: UZ
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "shakhzodallayorov23@gmail.com",
  "password": "User1234@"
}

###Verification By email
GET localhost:8080/auth/verification/email/eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg3ODI3ODYsImlkIjo3LCJleHAiOjE3MDg3ODMwODYsImlzcyI6Ikt1blV6VGVzdCJ9.aPfyNJlVv3zUhMLxMcqRtMbGiNa3trCfJv0dP3420megbsq_nnNcqOSQcP5O4W21jbWlNpGQE7VzreIURWCA7w
Accept-Language: EN


###Verification By phone number
POST localhost:8080/auth/verification/phone
Accept-Language: EN
Content-Type: application/json

{
  "code": "51188",
  "phoneNumber": "998991339906"
}

