### Creat
POST http://localhost:8080/channel/creat
Content-Type: application/json

Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MDYzNzYsImVtYWlsIjoiYXNhZGJla3hvamFtdXJvZG92NjhAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODY5Mjc3NiwiaXNzIjoiS3VuVXpUZXN0In0._-bRvF0Exb8F8CKJ2_t_nqc-Ymds5HmY0tSM_ZL24DvHratj2i-1VShd6Cmz8AFmiRa0T4UZP_ATgjToi8ZDIQ
Accept-Language: UZ

Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MjI3MTcsImVtYWlsIjoiaHVzZW50ZXNoYXlpdkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4NzA5MTE3LCJpc3MiOiJLdW5VelRlc3QifQ.yIClg3804-Re6jwtn-66SuccKEseMJXHeijWpzQeAuQyj0mh8f0hWDi_n7viQjG0Jr8vLyAothCV2c1w3vw4yQ


{
  "name": "Yangiliklar",
  "description": "Barcha turdagi yangiliklar",
  "photoId": "0994f7a7-5cfb-4180-9ff0-f11265a73e0a",
  "bannerId": "0994f7a7-5cfb-4180-9ff0-f11265a73e0a"
}

### Update Details
PUT http://localhost:8080/channel/update/4bde2295-4cf5-4f6f-9467-a5adb05157e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MjI3MTcsImVtYWlsIjoiaHVzZW50ZXNoYXlpdkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4NzA5MTE3LCJpc3MiOiJLdW5VelRlc3QifQ.yIClg3804-Re6jwtn-66SuccKEseMJXHeijWpzQeAuQyj0mh8f0hWDi_n7viQjG0Jr8vLyAothCV2c1w3vw4yQ

{
  "name": "Eski habarlar",
  "description": "Umumiy eski habarlar"
}

### Update Photo
PUT http://localhost:8080/channel/updatePhoto/4bde2295-4cf5-4f6f-9467-a5adb05157e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MjI3MTcsImVtYWlsIjoiaHVzZW50ZXNoYXlpdkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4NzA5MTE3LCJpc3MiOiJLdW5VelRlc3QifQ.yIClg3804-Re6jwtn-66SuccKEseMJXHeijWpzQeAuQyj0mh8f0hWDi_n7viQjG0Jr8vLyAothCV2c1w3vw4yQ

{
  "imageId": "2ff306e6-6286-4022-9f5e-229ec470a680"
}

### Update Banner
PUT http://localhost:8080/channel/updateBanner/4bde2295-4cf5-4f6f-9467-a5adb05157e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MjI3MTcsImVtYWlsIjoiaHVzZW50ZXNoYXlpdkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4NzA5MTE3LCJpc3MiOiJLdW5VelRlc3QifQ.yIClg3804-Re6jwtn-66SuccKEseMJXHeijWpzQeAuQyj0mh8f0hWDi_n7viQjG0Jr8vLyAothCV2c1w3vw4yQ

{
  "imageId": "2ff306e6-6286-4022-9f5e-229ec470a680"
}

### Get By Pagination
GET http://localhost:8080/channel/getByPagination
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg0MzcxMTUsImVtYWlsIjoic2FuamFyc3VsdGFub3YyMDI0QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4NTIzNTE1LCJpc3MiOiJLdW5VelRlc3QifQ.z-bxTqNGu9yqzKNoMgn7jBRjNeio_fXFaKkro0VH9tWgC0dMc8LSQKWA1h-jmt7bH45LO16Il_WTeo9czdPOgw

### Get By Id
GET http://localhost:8080/channel/getById/4bde2295-4cf5-4f6f-9467-a5adb05157e7

### Update Status
PUT http://localhost:8080/channel/updateStatus/4bde2295-4cf5-4f6f-9467-a5adb05157e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MjI3MTcsImVtYWlsIjoiaHVzZW50ZXNoYXlpdkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4NzA5MTE3LCJpc3MiOiJLdW5VelRlc3QifQ.yIClg3804-Re6jwtn-66SuccKEseMJXHeijWpzQeAuQyj0mh8f0hWDi_n7viQjG0Jr8vLyAothCV2c1w3vw4yQ

{
  "status": "BLOCK"
}

### Get List
GET http://localhost:8080/channel/getChannelList
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MjI3MTcsImVtYWlsIjoiaHVzZW50ZXNoYXlpdkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4NzA5MTE3LCJpc3MiOiJLdW5VelRlc3QifQ.yIClg3804-Re6jwtn-66SuccKEseMJXHeijWpzQeAuQyj0mh8f0hWDi_n7viQjG0Jr8vLyAothCV2c1w3vw4yQ
