### Creat
POST http://localhost:8080/channel/creat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDkwNjQxNDIsImVtYWlsIjoiYXNhZGJla3hvamFtdXJvZG92NjhAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwOTE1MDU0MiwiaXNzIjoiS3VuVXpUZXN0In0.fr6DZQ7TWFD-Yrnr0LY3Da5G9-3JyPs_tQ8UbnlSc2chCjAF-oDMlyvqK1exzaf7OFCoCE0WKpegMFruY-5Q4g
Accept-Language: UZ

{
  "name": "Kun uz",
  "description": "Kunnubg eng so'ngi yangiliklari",
  "photoId": "5087af77-a06d-41d0-9a66-06a9701503c0",
  "bannerId": "a667330e-e5c2-422d-a1f4-88c80b330b72"
}


### Update Details
PUT http://localhost:8080/channel/update/4bde2295-4cf5-4f6f-9467-a5adb05157e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MjI3MTcsImVtYWlsIjoiaHVzZW50ZXNoYXlpdkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4NzA5MTE3LCJpc3MiOiJLdW5VelRlc3QifQ.yIClg3804-Re6jwtn-66SuccKEseMJXHeijWpzQeAuQyj0mh8f0hWDi_n7viQjG0Jr8vLyAothCV2c1w3vw4yQ

{
  "name": "Eski habarlar",
  "description": "Umumiy eski habarlar"
}

### Update Photo
PUT http://localhost:8080/channel/updatePhoto/4bde2295-4cf5-4f6f-9467-a5adb05157e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MjI3MTcsImVtYWlsIjoiaHVzZW50ZXNoYXlpdkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4NzA5MTE3LCJpc3MiOiJLdW5VelRlc3QifQ.yIClg3804-Re6jwtn-66SuccKEseMJXHeijWpzQeAuQyj0mh8f0hWDi_n7viQjG0Jr8vLyAothCV2c1w3vw4yQ

{
  "imageId": "2ff306e6-6286-4022-9f5e-229ec470a680"
}

### Update Banner
PUT http://localhost:8080/channel/updateBanner/4bde2295-4cf5-4f6f-9467-a5adb05157e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MjI3MTcsImVtYWlsIjoiaHVzZW50ZXNoYXlpdkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4NzA5MTE3LCJpc3MiOiJLdW5VelRlc3QifQ.yIClg3804-Re6jwtn-66SuccKEseMJXHeijWpzQeAuQyj0mh8f0hWDi_n7viQjG0Jr8vLyAothCV2c1w3vw4yQ

{
  "imageId": "2ff306e6-6286-4022-9f5e-229ec470a680"
}

### Get By Pagination
GET http://localhost:8080/channel/getByPagination
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg0MzcxMTUsImVtYWlsIjoic2FuamFyc3VsdGFub3YyMDI0QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4NTIzNTE1LCJpc3MiOiJLdW5VelRlc3QifQ.z-bxTqNGu9yqzKNoMgn7jBRjNeio_fXFaKkro0VH9tWgC0dMc8LSQKWA1h-jmt7bH45LO16Il_WTeo9czdPOgw

### Get By Id
GET http://localhost:8080/channel/getById/4bde2295-4cf5-4f6f-9467-a5adb05157e7

### Update Status
PUT http://localhost:8080/channel/updateStatus/4bde2295-4cf5-4f6f-9467-a5adb05157e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MjI3MTcsImVtYWlsIjoiaHVzZW50ZXNoYXlpdkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4NzA5MTE3LCJpc3MiOiJLdW5VelRlc3QifQ.yIClg3804-Re6jwtn-66SuccKEseMJXHeijWpzQeAuQyj0mh8f0hWDi_n7viQjG0Jr8vLyAothCV2c1w3vw4yQ

{
  "status": "BLOCK"
}

### Get List
GET http://localhost:8080/channel/getChannelList
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MjI3MTcsImVtYWlsIjoiaHVzZW50ZXNoYXlpdkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4NzA5MTE3LCJpc3MiOiJLdW5VelRlc3QifQ.yIClg3804-Re6jwtn-66SuccKEseMJXHeijWpzQeAuQyj0mh8f0hWDi_n7viQjG0Jr8vLyAothCV2c1w3vw4yQ
