### create comment
POST localhost:8080/comment/create
#admin
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg3NTgyMzMsImVtYWlsIjoiaHVzZW50ZXNoYXlldjhAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg4NDQ2MzMsImlzcyI6Ikt1blV6VGVzdCJ9.6MPWfYVRebuXS6h3n_QGa9IljhvIhJV78Tbu_pOP6JKTemMGA5QhwaZDcpis87ZC8VVvhoF54xpf4ZRnFykYlA
#user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg3NTkyNzcsImVtYWlsIjoibW9kZXJhdG9yQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MDg4NDU2NzcsImlzcyI6Ikt1blV6VGVzdCJ9.9H-2mbKHZOpiP4RS-cqFUFqlskT7PErS8Nsv6WP13nTJ7vhifutrOvdoNrJzjYjRgWD6nR8QOzln5GhzoCgk-g
#user2
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg3NjEwNDYsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4ODQ3NDQ2LCJpc3MiOiJLdW5VelRlc3QifQ.UlTUTDZ8cLbEO292oOInGYhihRUMJ3ySj0vIlpNp5vMAeH7oasiGssRntCthN3diaJLKb6AGFCpm51yNzoyL2w
Accept-Language: UZ
Content-Type: application/json

{
  "content": "Good  Video👌👌👌👌",
  "videoID": "5377b750-db2b-4f75-b333-c991ace8be31"
}

### update comment
POST localhost:8080/comment/update/7
Accept-Language: UZ
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg3ODU5NjksImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODg3MjM2OSwiaXNzIjoiS3VuVXpUZXN0In0.vWsgp9BUlasBeKlsclPmUjQ907nvA5akzc9mb-_As_euJvWY_b95sLYN3wkFrx6xvSAEHUEG6cOd1OaCmHRtng
Content-Type: application/json

{
  "content": "GOOD Comment update👌👌"
}

### delete comment

DELETE localhost:8080/comment/delete/5
Accept-Language: UZ
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg3ODU5NjksImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODg3MjM2OSwiaXNzIjoiS3VuVXpUZXN0In0.vWsgp9BUlasBeKlsclPmUjQ907nvA5akzc9mb-_As_euJvWY_b95sLYN3wkFrx6xvSAEHUEG6cOd1OaCmHRtng
#user
#eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MTI4MDAsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4Njk5MjAwLCJpc3MiOiJLdW5VelRlc3QifQ.3d6YGD3lHO4Sh2udXyit_cwSWl--Btb7zhNtH5xh1XxCKeyUuhwiAyfLwgwmRAdsoRE2xFLedEoQyQX-eefnag

### pagination comment

GET localhost:8080/comment/adm/pagination?size=5&page=1
Authorization: Bearer

### paginarion comment profileID(ADMIN)
GET localhost:8080/comment/adm/paginationProfileID?size=2&page=2&id=3
Authorization: Bearer
Accept-Language: UZ

### paginarion comment profileId(USER,OWNER)
GET localhost:8080/comment/paginationProfileID?size=2&page=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg3ODU5NjksImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODg3MjM2OSwiaXNzIjoiS3VuVXpUZXN0In0.vWsgp9BUlasBeKlsclPmUjQ907nvA5akzc9mb-_As_euJvWY_b95sLYN3wkFrx6xvSAEHUEG6cOd1OaCmHRtng
#user(id=3,comment yozgan)
#eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2NjkzMDMsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4NzU1NzAzLCJpc3MiOiJLdW5VelRlc3QifQ.1ICtqSiwTkVFRdeymFrUOenZ0v1tVfxdTNacSejevexzIaukATc3IL7bpdFulfPsuWKF_JCLVl3zIxPWA1tWNQ
#user(id=5,comment yozgan)
#eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2NjkzODcsImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODc1NTc4NywiaXNzIjoiS3VuVXpUZXN0In0.fSmU6zietZ7ZkdCCQmvvEPwjjLUGeREBt5KpgM_h183c8z9w41nZ2Olz6kn0_RbJoxI_60AkWhZBh_yp2v0sog
#user(id=6,comment yozmagan)
#eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2Njk3NTYsImVtYWlsIjoidXNlcmFsaUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzA4NzU2MTU2LCJpc3MiOiJLdW5VelRlc3QifQ.0Go_JmkzwKXgarFKpgC_t-K35udcviw3wcknBUDvpovlLBpOfczYjvfBA_mRZV6HieuPf3LUx6sYW5G6hIvB3g
Accept-Language: UZ
### getList comment (VideoID)
GET localhost:8080/comment/getListVideo/e8009202-b1b0-45de-9bd9-88932c6fbce8
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg3ODU5NjksImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODg3MjM2OSwiaXNzIjoiS3VuVXpUZXN0In0.vWsgp9BUlasBeKlsclPmUjQ907nvA5akzc9mb-_As_euJvWY_b95sLYN3wkFrx6xvSAEHUEG6cOd1OaCmHRtng
Accept-Language: UZ

### getList comment (replyID)
GET localhost:8080/comment/replyList/3
Accept-Language: UZ



