###Create Profile
POST localhost:8080/profile/adm
#admin
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgzNjA0MjgsImVtYWlsIjoic2FuamFyZGFzdHVyY2hpQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4NDQ2ODI4LCJpc3MiOiJLdW5VelRlc3QifQ.cLlepkJ3YNV_MWcv1uBKnqJiru7Tto5x4_4yG3ulMpw-75xgUsh67ESYYLAcFcGtwdA8L99hLIbQLG1mPl9JoA
Content-Type: application/json

{
  "name": "Moderator",
  "surname": "Moderatorov",
  "email": "moderator@gmail.com",
  "password": "$1Moderator1$",
  "role": "ROLE_USER"
}

###Change Password
POST localhost:8080/profile/any/@1Moderator1@
Accept-Language: RU
#moderator
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgzNjAxNjAsImVtYWlsIjoibW9kZXJhdG9yQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTcwODQ0NjU2MCwiaXNzIjoiS3VuVXpUZXN0In0.rKHnsJYuyNtvmS5BAW67wpLhpapSomAt1IYnsMfEFYaFFbF1M5sYKPEykX6y6TiD0Xpbh3Rb6b4hEaL2WQtsBA

###Update Email
POST localhost:8080/profile/any
Accept-Language: RU
#moderator
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg0OTkxNTgsImVtYWlsIjoibW9kZXJhdG9yQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTcwODU4NTU1OCwiaXNzIjoiS3VuVXpUZXN0In0.2soLgfWw3Vu6m7dMUhFvQ3NzgcFrLywtiVVKKXQKHGaFN5H6I0KRJRS77NGSAkkbpZmFPR74IabNucCMgZX2gw
#user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1MjE5ODMsImVtYWlsIjoiaHVzZW50ZXNoYXlldjhAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODYwODM4MywiaXNzIjoiS3VuVXpUZXN0In0.AQIDpI3EWLtOFJhWKpwag7QjFN5VxvZqbMJ1SmBb2E4s4-Ka33mKX0-LwpUfapHAqh_3oKZdNjVJvNLIjXQJ2A
Content-Type: application/json

{
  "email": "sanjarbeksultanov2023@gmail.com"
}
###Verification for update email
GET localhost:8080/profile/verification/email/eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1MjMzNDgsImVtYWlsIjoic2FuamFyYmVrc3VsdGFub3YyMDIzQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpZCI6MTMsImV4cCI6MTcwODYwOTc0OCwiaXNzIjoiS3VuVXpUZXN0In0.ss5i7K0v37MTDQFfblpcmzSEeeoGAY9VkAwY3N4bAktf3UEqZpUoIpgt5K3_N8iNqI_lAosb1XE-dsi3k7JLVQ
Accept-Language: EN

###Update detail
POST localhost:8080/profile/any/detail
Accept-Language: RU
#moderator
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg0OTkxNTgsImVtYWlsIjoibW9kZXJhdG9yQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTcwODU4NTU1OCwiaXNzIjoiS3VuVXpUZXN0In0.2soLgfWw3Vu6m7dMUhFvQ3NzgcFrLywtiVVKKXQKHGaFN5H6I0KRJRS77NGSAkkbpZmFPR74IabNucCMgZX2gw
#user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1MDI2MzcsImVtYWlsIjoiaHVzZW50ZXNoYXlldjhAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODU4OTAzNywiaXNzIjoiS3VuVXpUZXN0In0.QYcdsy1hTOhrRu7v3IWwCS49rpiHKfis0-OuqE0-IbKUti2vQUo2nDGwSroGe0dPSAAmvmAV6I4OzBs3J5SPsg
Content-Type: application/json

{
  "name": "ali",
  "surname": "aliyev"
}


