### Create video
POST http://localhost:8080/video/create
Content-Type: application/json

{
  "title": "USAdagi O'zbeklar",
  "description": "Yevropadagi hayot haqida bilib olamiz",
  "attachId": "de36f0f5-69a1-4fb3-8131-d5aa00bdcf40",
  "categoryId": 1,
  "channelId": "3fe9bb21-83f4-4eea-b299-f77f5d63a78d",
  "previewAttachId": "edf3cf6b-3c5c-4b3e-b103-1dd18e21fb75",
  "videoStatus": "PUBLIC",
  "videoType": "VIDEO"
}


### Update
PUT http://localhost:8080/video/update/8db5a764-5d44-4b64-9094-d9189ad83311
Content-Type: application/json

{
  "description": "Yevropadagi hayot haqida O'zbekistonliklardan eshitamiz"
}

### Update status
PUT http://localhost:8080/video/updateStatus/8db5a764-5d44-4b64-9094-d9189ad83311
Content-Type: application/json

{
  "videoStatus": "PRIVATE"
}


### Update view count
PUT http://localhost:8080/video/increaseViewCountByVideoId/8db5a764-5d44-4b64-9094-d9189ad83311
Content-Type: application/x-www-form-urlencoded


### Pagination
GET http://localhost:8080/video/paginationCategoryId?category=5


### Search
GET http://localhost:8080/video/search?title=vro


### Get by id
GET http://localhost:8080/video/getById/8db5a764-5d44-4b64-9094-d9189ad83311


### Pagination video list
GET http://localhost:8080/video/videoList


### Pagination by channelId
GET http://localhost:8080/video/channelVideoList/d72b61cb-e0f6-49be-a41d-2e2cea7518d7

