### Create video
POST http://localhost:8080/video/create
Accept-Language: RU
Content-Type: application/json

{
  "title": "Yevropadagi O'zbeklar",
  "description": "Yevropadagi hayot haqida bilib olamiz",
  "attachId": "b8c9c96c-005d-4793-abd3-6a4faab45507",
  "categoryId": 5,
  "channelId": "852af6b4-ea6c-4aa4-a108-b6818e64db9b",
  "previewAttachId": "5cf4b677-ec45-417b-a27e-36a1c4e5b9e2",
  "videoStatus": "PUBLIC",
  "videoType": "VIDEO"
}


### Update
PUT http://localhost:8080/video/update/8db5a764-5d44-4b64-9094-d9189ad83311
Content-Type: application/json

{
  "description": "Yevropadagi hayot haqida O'zbekistonliklardan eshitamiz"
}

### Update status
PUT http://localhost:8080/video/updateStatus/8db5a764-5d44-4b64-9094-d9189ad83311
Content-Type: application/json

{
  "videoStatus": "PRIVATE"
}


### Update view count
PUT http://localhost:8080/video/increaseViewCountByVideoId/8db5a764-5d44-4b64-9094-d9189ad83311
Content-Type: application/x-www-form-urlencoded


### Pagination
GET http://localhost:8080/video/paginationCategoryId?category=5


### Search
GET http://localhost:8080/video/search?title=vro


### Get by id
GET http://localhost:8080/video/getById/8db5a764-5d44-4b64-9094-d9189ad83311


### Pagination video list
GET http://localhost:8080/video/videoList


### Pagination by channelId
GET http://localhost:8080/video/channelVideoList/d72b61cb-e0f6-49be-a41d-2e2cea7518d7

