insert into tags (tag_name, created_date)
values('#cook', current_timestamp),
('#chef', current_timestamp),
('#diet', current_timestamp),
('#fastfood', current_timestamp),
('#live', current_timestamp),
('#funny', current_timestamp),
('#comedy', current_timestamp),
('#lol', current_timestamp),
('#trending', current_timestamp),
('#meme', current_timestamp),
('#tech', current_timestamp),
('#smartphone', current_timestamp),
('#mobile', current_timestamp),
('#game', current_timestamp),
('#pubg', current_timestamp),
('#playstation', current_timestamp),
('#minecraft ', current_timestamp),
('#teaching', current_timestamp),
('#learning', current_timestamp),
('#support', current_timestamp),
('#goals', current_timestamp),
('#like', current_timestamp),
('#technology', current_timestamp),
('#video', current_timestamp),
('#vlog', current_timestamp),
('#newvideo', current_timestamp),
('#motivation', current_timestamp),
('#facts', current_timestamp);

